spring:
  application:
    name: Observability Demo Application
  config:
    import: optional:classpath:.env.properties
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    user:
      name: test
      password: test

info:
  name: \${spring.application.name}
  version: ${version}
  profile: \${spring.profiles.active}
  
server:
  port: 8080
  error:
    include-message: always
    
management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    circuitbreaker:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info, health, prometheus
        
weatherapi:
  apikey: \${WEATHERAPI_APIKEY}
database:
  url: \${DATABASE_URL}
  user: \${DATABASE_USER}
  password: \${DATABASE_PASSWORD}
